apiVersion: apps/v1
kind: Deployment
metadata:
  name: zephyr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zephyr
  template:
    metadata:
      labels:
        app: zephyr
    spec:
      containers:
      - name: gateway
        image: zephyr:latest
        ports:
        - containerPort: 8080
