openapi: 3.0.0
info:
  title: Zephyr API
  version: 1.0.0
paths:
  /functions/deploy:
    post:
      summary: Deploy a new function
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                dockerfilePath:
                  type: string
                triggerType:
                  type: string
      responses:
        '201':
          description: Function deployed successfully
